/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: '#1A237E',
          dark: '#0D1642',
          light: '#3949AB',
        },
        bank: {
          purple: '#1A237E',
          purpleMid: '#283593',
          purpleDeep: '#0D1642',
          panel: '#E8EAF6',
          gold: '#FFD600',
          goldDark: '#F9A825',
          nav: '#1A237E',
        },
        dcb: {
          navy: '#1A237E',
          header: '#B3D4FC',
          yellow: '#FFD600',
          pink: '#F8E8E0',
          voice: '#7C4DFF',
          debit: '#D32F2F',
          credit: '#388E3C',
          page: '#F5F7FA',
        },
        optimo: {
          orange: '#E85D3B',
          orangeLight: '#FF8A65',
          navy: '#1B2B4B',
          bg: '#F8FAFF',
          pill: '#FFF5F0',
        },
        abcd: {
          red: '#C41E24',
          redDark: '#A8181E',
          yellow: '#F5C518',
          cream: '#F7F0E8',
          creamSoft: '#FFF8EE',
          page: '#FFFFFF',
          ink: '#1A1A1A',
          muted: '#6B7280',
          mint: '#E8F5E9',
          pink: '#FCE4EC',
          explore: '#C41E24',
        },
        accent: '#F5C518',
        success: '#388E3C',
        page: '#FFFFFF',
        ink: '#1A1A1A',
        muted: '#6B7280',
        divider: '#E5E7EB',
      },
      boxShadow: {
        card: '0 6px 18px rgba(14, 36, 84, 0.08)',
        bankCard: '0 8px 24px rgba(0, 0, 0, 0.35)',
        goldGlow: '0 0 0 1px rgba(245, 197, 24, 0.45), 0 12px 32px rgba(0, 0, 0, 0.4)',
        abcdCard: '0 2px 10px rgba(0, 0, 0, 0.06)',
      },
      fontFamily: {
        sans: [
          'Roboto',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'sans-serif',
        ],
      },
    },
  },
  plugins: [],
};
